### ISSUE TITLE
New MSI Installer ToDo's

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#2709]
- [x] Update download page for silent install & parameters
  -  [x] Add note to signpath about code signing cert
- [x] Update PowerShell Module Evergreen
- [x] Update WinGet
- [x] Update Chocolatey
- [x] Update release notes about new installer & signpath & uninstall innosetup version

**Comment by BornToBeRoot** [comment]
Evergreen PR: https://github.com/aaronparker/evergreen/pull/693

**Comment by BornToBeRoot** [comment]
Winget PR: https://github.com/microsoft/winget-pkgs/issues/157142
